### PR TITLE
Driver update - R8

### PR DESCRIPTION
**Pull request by cjourdan-movidius**
Update drivers based on MDK R8.

### CODE REVIEW

**Comment by simonabarrett** [comment]
@cjourdan-movidius  I cant review this Cyril as its out of my skills area . Should we ask Stavros or someone that knows more about the subject?

**Comment by cjourdan-movidius** [comment]
To be honest, I'm not expecting a technical review here, everything has been validated in MDK repo already. More a validation that the code integration seems correct compared to what's in the MDK repo.

**Comment by cjourdan-movidius** [comment]
But feel free to add anyone you think would be useful here.

**Comment by simonabarrett** [comment]
Got it now. We will have a look on that and review. Thank you!

**Pull request merged**
